version: 2
updates:
  # For npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "security"
      - "dependencies"
    
  # For GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    
  # For Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
